//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourAgentstvo.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data
    {
        public int id { get; set; }
        public int type { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        public virtual roles roles { get; set; }
    }
}
